version: 2.0
jobs:
  build:
    docker:
      - image: typelead/eta:latest
    steps:
    - checkout

    - restore_cache:
        key: v1200-etlas-cache-

    - run: etlas update

    - save_cache:
        key: v1200-etlas-cache-{{ epoch }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          - "~/.etlas/patches"
          - "~/.etlas/tools"

    - run: etlas install

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
